name: Famous Quotes

on: 
  push: 
    branches: [playBranch]

jobs: 
  MyFavQuotes:
    runs-on: ubuntu-latest

    steps: 
      - name: Step1
        run: echo "It is better to have loved and lost than to have never loved" 

      - name: Step2
        run: echo "Carpe Diem"

